# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmiC5jlSa_alkVRMnoLHR9fWz7Q5T7zX
"""

scores=list(map(int,input().split()))
fail_count=sum(1 for s in scores if s<60)
print(fail_count)